const username = 'Admin';
const userpass = 'admin123';
describe('UI Tests', () => {
  it('1', () => {
   cy.visit('https://www.google.com/')
   cy.get('.gLFyf').type('USA')
   cy.get("div[class='lJ9FBc'] input[name='btnK']").click()
   cy.get('.LC20lb.MBeuO.DKV0Md').contains('United States').click()
  })
  it('2', () => {
   cy.visit('https://www.amazon.com/')
   cy.get('#twotabsearchtextbox').type('iphone')
   cy.get('#nav-search-submit-button').click()
   cy.get('#high-price').type('200')
   cy.get('.a-button-input').click()
   cy.get('[data-asin="B088NDPK5T"] > :nth-child(1) > .s-widget-container > .s-card-container > :nth-child(1) > :nth-child(1) > .sg-col-8-of-16 > :nth-child(1) > .a-spacing-top-small > .puis-padding-right-small > .a-size-mini > .a-link-normal > .a-size-medium').should('exist')
   cy.get('[data-asin="B088NDPK5T"] > :nth-child(1) > .s-widget-container > .s-card-container > :nth-child(1) > :nth-child(1) > .sg-col-8-of-16 > :nth-child(1) > .a-spacing-top-small > .sg-row > .sg-col-4-of-20 > .sg-col-inner > .s-color-swatch-container-list-view > .s-color-swatch-container > :nth-child(3) > div > .a-link-normal > .s-color-swatch-inner-circle-fill > .s-color-swatch-inner-circle-border').click()
  })
  it('3', () => {
    cy.viewport(1920, 1080)
    cy.visit('https://demoqa.com/')
    cy.contains('.card-body', 'Forms').click()
    cy.contains('.text', 'Practice Form').click()
    cy.get('[id="dateOfBirthInput"]').click()
    cy.get(':nth-child(6) > .react-datepicker__day--003').click()
    cy.get('[id="dateOfBirthInput"]').invoke('attr', 'value').should('contain', '03 Aug 2023')
   })
   it('4', () => {
    cy.viewport(1920, 1080)
    cy.visit('https://opensource-demo.orangehrmlive.com/')
    cy.get('[placeholder="Username"]').type(username)
    cy.get('[placeholder="Password"]').type(userpass)
    cy.get('[type="submit"]').click()
    cy.url().should('contain', '/dashboard/index')
   })
   it('5', () => {
    cy.viewport(1920, 1080)
    cy.visit('https://opensource-demo.orangehrmlive.com/')
    cy.get('[placeholder="Username"]').type(username)
    cy.get('[placeholder="Password"]').type(userpass)
    cy.get('[type="submit"]').click()
    cy.url().should('contain', '/dashboard/index')
    cy.contains('[class="oxd-main-menu-item-wrapper"]', 'Admin').click()
    cy.get('[class="oxd-input oxd-input--active"]').eq(1).type('Admin')
    //cy.get('[class="oxd-input-group oxd-input-field-bottom-space"]').eq(0).find('[class="oxd-input oxd-input--active"]').type('Svyat')
    cy.get('[class="oxd-icon bi-caret-down-fill oxd-select-text--arrow"]').eq(0).click({force: true})
    cy.get('[class="oxd-select-option"]').eq(1).click()
    cy.get('[class="oxd-select-text-input"]').should('contain', 'Admin')
    cy.get('[placeholder="Type for hints..."]').type('Paul')
    .wait(5000)
    cy.get('[class="oxd-autocomplete-option"]').click()
    cy.get('[class="oxd-select-text oxd-select-text--active"]')
    .find('[class="oxd-select-text-input"]').eq(1).click({force: true})
    cy.get('[class="oxd-select-dropdown --positon-bottom"]').find('[class="oxd-select-option"]').eq(1).click()
    cy.get('[type="submit"]').click({force: true})
   })
   it('6', () => {
    cy.viewport(1920, 1080)
    cy.visit('https://opensource-demo.orangehrmlive.com/')
    cy.get('[placeholder="Username"]').type(username)
    cy.get('[placeholder="Password"]').type(userpass)
    cy.get('[type="submit"]').click()
    cy.url().should('contain', '/dashboard/index')
    cy.contains('[class="oxd-main-menu-item-wrapper"]', 'Admin').click()
    cy.contains('[type="button"]', 'Add').click()
    cy.contains('[class="oxd-label oxd-input-field-required"]', 'User Role')
    .closest('[class="oxd-input-group__label-wrapper"]').next('[data-v-957b4417]').click()
    cy.contains('[class="oxd-select-option"]', 'Admin').click()
    cy.get('[class="oxd-select-text oxd-select-text--active"]').eq(0).should('contain', 'Admin')
    cy.contains('[class="oxd-label oxd-input-field-required"]', 'Status')
    .closest('[class="oxd-input-group__label-wrapper"]').next('[data-v-957b4417]').click()
    cy.contains('[class="oxd-select-option"]', 'Enabled').click()
    cy.get('[class="oxd-select-text oxd-select-text--active"]').eq(1).should('contain', 'Enabled')
    cy.get('[class="oxd-autocomplete-text-input oxd-autocomplete-text-input--active"]').type('Alice')
    .wait(5000).next('[class="oxd-autocomplete-dropdown --positon-bottom"]').click()
    cy.contains('[class="oxd-label oxd-input-field-required"]', 'Username')
    .closest('[class="oxd-input-group__label-wrapper"]').next('[data-v-957b4417]').find('input').type('Egor1')
    .invoke('val').should('have.length.at.least', 5)
    cy.get('[type="password"]').eq(0).type('ABc123_').invoke('val').should('have.length.at.least', 7).should('match', /[a-z]/)
    cy.get('[type="password"]').eq(1).type('ABc123_').invoke('val').should('have.length.at.least', 7).should('match', /[a-z]/)
    cy.contains('[type="submit"]', 'Save').click()
    cy.get('[class="oxd-toast oxd-toast--success oxd-toast-container--toast"]').should('exist')
   })
   it.only('7', () => {
    cy.viewport(1920, 1080)
    cy.visit('https://opensource-demo.orangehrmlive.com/')
    cy.get('[placeholder="Username"]').type(username)
    cy.get('[placeholder="Password"]').type(userpass)
    cy.get('[type="submit"]').click()
    cy.url().should('contain', '/dashboard/index')
    cy.contains('Claim').closest('[class="oxd-main-menu-item"]').click()
    cy.url().should('contain', '/claim/viewAssignClaim')
    cy.contains('Assign Claim').click()
    cy.url().should('contain', '/claim/assignClaim')
    cy.get('[placeholder="Type for hints..."]').type('be').wait(3000)
    .closest('div').next('[class="oxd-autocomplete-dropdown --positon-bottom"]').click()
    cy.get('[placeholder="Type for hints..."]').invoke('val').should('contain', 'Carlos Roberto Nieto')
    cy.get('[class="oxd-select-text oxd-select-text--active"]').eq(0).click()
    cy.contains('[class="oxd-select-option"]', 'Accommodation').click()
    const event = 'Accommodation'
    cy.get('[class="oxd-select-text oxd-select-text--active"]')
    .find('[class="oxd-select-text-input"]').invoke('text').should('contain', event)
    cy.get('[class="oxd-select-text oxd-select-text--active"]').eq(1).click()
    cy.contains('[class="oxd-select-option"]', 'North Korean Won').click()
    const currency = 'North Korean Won'
    cy.get('[class="oxd-select-text oxd-select-text--active"]').invoke('text').should('contain', currency)
    cy.get('[class="oxd-textarea oxd-textarea--active oxd-textarea--resize-vertical"]').type('Want to Spain')
    cy.contains('[type="submit"]', 'Create').click()
    cy.get('[class="oxd-toast oxd-toast--success oxd-toast-container--toast"]').should('exist').wait(3500)
    cy.contains('[type="button"]', 'Submit').scrollIntoView().click()
    cy.get('[class="oxd-toast oxd-toast--success oxd-toast-container--toast"]').should('exist')
    cy.contains('[class="oxd-button oxd-button--medium oxd-button--ghost orangehrm-sm-button"]', 'Back').click()
    cy.url().should('contain', '/claim/viewAssignClaim')
  }) 
})